ClassLength:
  Max: 400

CyclomaticComplexity:
  Max: 10

PerceivedComplexity:
  Enabled: false

Documentation:
  Enabled: false

FileName:
  Enabled: false

AbcSize:
  Enabled: false

LineLength:
  Max: 93
