ClassLength:
  Max: 400

CyclomaticComplexity:
  Max: 10

PerceivedComplexity:
  Enabled: false

Documentation:
  Exclude:
    - lib/lita/handlers/statuspage.rb

FileName:
  Exclude:
    - lib/lita-statuspage.rb

AbcSize:
  Enabled: false

LineLength:
  Max: 130
